app.controller('sellerController',function($scope,sellerService){
	$scope.add=function(){
		sellerService.add($scope.entity).success(
				function(response){
					if(response.success){
						location.href="shoplogin.html";
					}else{
						alert(response.message);
					}
				}
		)
	}
})