app.controller('sellerController' ,function($scope,$controller,sellerService){
			$controller('baseController',{$scope:$scope});//继承
	        //读取列表数据绑定到表单中
			$scope.findAll=function(){
				sellerService.findAll().success(
					function(response){
						$scope.list=response;
					}			
				);
			}
			//分页
			$scope.findPage=function(page,rows){	
				sellerService.findPage(page,rows).success(
						function(response){
							$scope.list=response.rows;	
							$scope.paginationConf.totalItems=response.total;//更新总记录数
						}
				);
			}
			$scope.searchEntity={};//定义搜索对象 
			//条件查询 
			$scope.search=function(page,rows){
				sellerService.search(page,rows,$scope.searchEntity).success(
					function(response){
							$scope.paginationConf.totalItems=response.total;//总记录数 
							$scope.list=response.rows;//给列表变量赋值 
					}		
				);				
			}
			//查询实体 
			$scope.findOne=function(id){
				sellerService.findOne(id).success(
						function(response){
							$scope.entity= response;					
					     }
				);				
			}
			$scope.updateStatus=function(status){
				sellerService.updateStatus(status,$scope.entity).success(
						function(response){
							if(response.success){
								//重新查询 
								 $scope.reloadList();//重新加载
							 }else{
								 alert(response.message);
							 }
						}		
					);
			}
		});
